# HTTP Server
[server]
host = "localhost"
port = 8080

# HTTPS Server
#[https]
#port = 8083
#cert = "certs/synclink.ptdg.dev.crt"
#key = "certs/synclink.ptdg.dev.key"

# File storage
[file_storage]
storage_path = ".storage"

# logger
[log]
level = "debug"