[package]
name = "synclink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.12", features = ["default", "multipart", "macros"] }
chrono = "0.4.24"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
sha2 = "0.10.6"
tokio = { version = "1.26.0", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["full"] }
async-stream = "0.3.5"
toml = "0.7.3"
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tracing-error = "0.2.0"
anyhow = "1.0.71"
thiserror = "1.0.40"
uuid = { version = "1.3.0", features = ["v4", "serde"] }
mime_guess = "2.0.4"
infer = "0.13.0"