# HTTP Server
[server]
host = "::"
port = 8080

# File storage
[file_storage]
storage_path = "storage"
#quota = 240g
#max_size_of = 120m

# logger
[logs]
level = "debug"
#storage_path = "logs"

# Authorize
#[authorize]
#secret = ""

#[device_ip_tags]
#"192.168.1.1" = "My computer"