[package]
name = "sha256"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.86"
sha2 = "0.10.6"

[lib]
crate-type = ["cdylib"]